name: Index Docs in Opper
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  index-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Index docs in Opper
        uses: opper-ai/opper-index-action@v1.1.1
        with:
          folder: '.'
          apikey: ${{ secrets.OPPER_API_KEY_CHATBOT }}
          index: 'opper-docs'

  index-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Index docs in Opper
        uses: opper-ai/opper-index-action@v1.1.1
        with:
          folder: './examples'
          apikey: ${{ secrets.OPPER_API_KEY_CHATBOT }}
          index: 'opper-docs'
          file_types: '.py'
